In [144]:
import numpy as np

def solution(a): 
    size=len(a)
    a=np.array(a)
    b=np.zeros([size,size])
    def plus(A,i,j):
        if i==0:
            for x in range(i,i+2):
                if j==0:
                    for y in range(j,j+2):
                        A[x,y]+=1
                elif j==size:
                    for y in range(j-1,j+1):
                        A[x,y]+=1
                else:
                    for y in range(j-1,j+2):
                        A[x,y]+=1
        elif i==size:
            for x in range(i-1,i+1):
                if j==0:
                    for y in range(j,j+2):
                        A[x,y]+=1
                elif j==size:
                    for y in range(j-1,j+1):
                        A[x,y]+=1
                else:
                    for y in range(j-1,j+2):
                        A[x,y]+=1
        else:
            for x in range(i-1,i+2):
                if j==0:
                    for y in range(j,j+2):
                        A[x,y]+=1
                elif j==size:
                    for y in range(j-1,j+1):
                        A[x,y]+=1
                else:
                    for y in range(j-1,j+2):
                        A[x,y]+=1
    for i in range(size-1):
        for j in range(size-1):
            if a[i,j]!=0:
                plus(b,i,j)
    return a, b, sum(([list(list(b)[i]).count(0) for i in range(size)]))

In [5]:
import numpy as np

In [146]:
a=[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0]]

In [147]:
solution(a)

(array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 2., 2., 1.],
        [0., 1., 2., 2., 1.],
        [0., 1., 2., 2., 1.]]),
 13)

In [50]:
b=np.zeros([3,3])
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
[i for i in range(1)]

[0]