In [1]:
# 안전지대

In [2]:
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0]]	16
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0]]	13
[[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]	0

SyntaxError: invalid syntax (1788383378.py, line 1)

In [55]:
import numpy as np
def solution(a):
    
    A=a
    R=np.zeros([len(A),len(A)])
    
    def cut_range(idx):
        if idx==0:
            return [idx,idx+1]
        elif idx==len(A)-1:
            return [idx-1,idx]
        else:
            return [idx-1,idx,idx+1]
        
    for i in range(len(A)):
        for j in range(len(A)):
            if A[i][j]!=0:
                for x in cut_range(i):
                    for y in cut_range(j):
                        R[x,y]=1
    result=0
    for a in list(R):
        result+=list(a).count(0)
    return result

In [56]:
solution([[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]])

0

In [16]:
A=np.array([[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0]])

In [17]:
for a in A:
    a+=1
A

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 2, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
list(range(0,1))

[0]

In [25]:
def solution(A):
    cpy_x=[[0 for i in range(len(A))] for j in range(len(A))]
    def rang(x=int):
        if x==0:
            return [0,1]
        elif x==len(A)-1:
            return [len(A)-2,len(A)-1]
        else:
            return [x-1,x,x+1]
        
    for x in range(len(A)):
        for y in range(len(A)):
            if A[x][y]!=0:
                for i in rang(x):
                    for j in rang(y):
                        cpy_x[i][j]=1
    result=0
    for x in range(len(A)):
        result+=cpy_x[x].count(0)
    return result

In [26]:
solution([[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]])

0

In [11]:
import numpy as np
def solution(array):
    A=np.array(array)
    Z=np.zeros([len(A),len(A)])
    
    for i in range(len(A)-1):
        for j in range(len(A)-1):
            if A[i,j]==1:
                if i==0:
                    if j==0:
                        for i in [0,1]:
                            for j in [0,1]:
                                Z[i,j]=1
                    elif j==len(A):
                        for i in [0,1]:
                            for j in [len(A)-1,len(A)]:
                                Z[i,j]=1
                    else:
                        for i in [0,1]:
                            for j in [j-1,j,j+1]:
                                Z[i,j]=1
                elif i==len(A):
                    if j==0:
                        for i in [len(A)-1,len(A)]:
                            for j in [0,1]:
                                Z[i,j]=1
                    elif j==len(A):
                        for i in [len(A)-1,len(A)]:
                            for j in [len(A)-1,len(A)]:
                                Z[i,j]=1
                    else:
                        for i in [len(A)-1,len(A)]:
                            for j in [j-1,j,j+1]:
                                Z[i,j]=1
                else:
                    if j==0:
                        for i in [i-1,i,i+1]:
                            for j in [0,1]:
                                Z[i,j]=1
                    elif j==len(A):
                        for i in [i-1,i,i+1]:
                            for j in [len(A)-1,len(A)]:
                                Z[i,j]=1
                    else:
                        for i in [i-1,i,i+1]:
                            for j in [j-1,j,j+1]:
                                Z[i,j]=1
        return Z
            

In [12]:
solution([[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
B=np.zeros([3,3])

In [8]:
B[0,0]=1
B

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
list(range(1,3))

[1, 2]

In [39]:
def solution(array):
    def ran(x=int):
        if x==0:
            return [0,1]
        elif x==len(array)-1:
            return [len(array)-2,len(array)-1]
        else:
            return [x-1,x,x+1]
    if len(array)==1:
        return array[0].count(0)
    else:
        sol=[[0 for i in range(len(array))] for j in range(len(array))]
        for i in range(len(array)):
            for j in range(len(array)):
                if array[i][j]==1:
                    for x in ran(i):
                        for y in ran(j):
                            sol[x][y]=1
    return sum([sol[i].count(0) for i in range(len(sol))])

In [40]:
solution([[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0]])

13